### ISSUE TITLE
Why two arduinos?

### ISSUE THREAD

**Issue by asiniy** [MarginallyClever/MDB-Sniffer#1]
It seems you can use just one arduino mega with two serial connections: 1 to pc, 1 to vending periphery

**Comment by perdidor** [comment]
it's enough to use only ONE Atmega1284, key to success is two hardware UARTs on chip. See my comment in other thread of this repo, it contains youtube link.

**Comment by i-make-robots** [comment]
two arduinos was what I had at the time.  two arduinos was cheaper than one mega.  IIRC I was told by others that one mega could not successfully talk to the VM and the PC at the same time, the clock was not fast enough.  I didn't independently verify that claim.
