### ISSUE TITLE
Optocouplers are really needed?

### ISSUE THREAD

**Issue by beckmx** [MarginallyClever/MDB-Sniffer#2]
I saw the circuitry, I was wondering if the optocouplers are really needed since the RX and TX are 5v already

**Comment by i-make-robots** [comment]
It's safer to leave them in.

**Comment by beckmx** [comment]
btw another question if you remember the code, there is this function which is suppose to receive info from the pc/raspberry I think is the "rpi_read()" but it is empty, I guess I send like an alias message and then execute the other functions mdb_write? looks like everything is in there just that part is a doubt to me

**Comment by i-make-robots** [comment]
that part of the code was never finished.
