### ISSUE TITLE
How to on off vending machine from arduino.

### ISSUE THREAD

**Issue by mppaes** [MarginallyClever/MDB-Sniffer#3]
How to on off vending machine from arduino.

**Comment by i-make-robots** [comment]
This question does not make sense.  on off what part in vending machine?  

on/off ENTIRE vending machine is not possible with MDB.

**Comment by serendependy** [comment]
IIRC you can pull the master transmit line high for >= 100ms to make the peripherals reset, but the VMC is supposed to do that so I imagine it's not something you can rely on working. It's also not something you can / should do for extended amount times to bring the machine down.
